version: '3.5'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=geolocalia
    ports:
      - 54329:5432
  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
        PGADMIN_DEFAULT_PASSWORD: "1234567890"
      ports:
        - "801:80"
      depends_on:
        - postgres
  fastapi:
    restart: always
    build:
      dockerfile: docker/fastapi.dockerfile
    working_dir: /usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    ports:
      - 8001:8000
    environment:
      DEBUG: 1
    volumes:
    - ./:/usr/src/app
networks:
  default:
    driver: bridge
